In [2]:
from config import api_key
from yelpapi import YelpAPI
import requests
import pandas as pd
import numpy as np
from pprint import pprint
import matplotlib.pyplot as plt

In [3]:
cities = ["Anaheim,CA", "Santa Ana,CA", "Irvine,CA", "Huntington Beach,CA", "Garden Grove,CA", "Orange,CA", "Fullerton,CA", "Costa Mesa,CA", "Mission Viejo,CA","Westminster,CA"]
url = "https://api.yelp.com/v3/businesses/search"
headers = {'Authorization': 'Bearer %s' %api_key}
price_locations = {}

for city in cities:
    locations={}
    params = {"term":"restaurant",
              "location":city,
              "limit":50,
             "radius":10000}
    responses=requests.get(url,headers = headers, params = params).json()
    for response in responses["businesses"]:
        try:
            money= response["price"]
            if money not in locations:
                locations[money]=1
                
            else:
                locations[money]+=1
        except KeyError:
            continue  
    price_locations[city]=locations 
    url_params = {"term":"restaurant",
                  "location":city,
                  "limit":50,
                 "offset":50,
                 "radius":10000}
    results = requests.get(url,headers = headers, params = url_params).json()
    for r in results["businesses"]:
        try:
            m = r["price"]
            if m not in locations:
                locations[m]=1
            else:
                locations[m]+=1
        except KeyError:
            continue
    price_locations[city]=locations
print(price_locations)

{'Anaheim,CA': {'$$': 58, '$$$': 8, '$': 31, '$$$$': 3}, 'Santa Ana,CA': {'$$': 53, '$$$$': 1, '$': 43, '$$$': 1}, 'Irvine,CA': {'$$': 70, '$$$': 7, '$': 22}, 'Huntington Beach,CA': {'$$': 69, '$': 25, '$$$': 4}, 'Garden Grove,CA': {'$$': 45, '$': 51, '$$$': 1, '$$$$': 2}, 'Orange,CA': {'$$': 52, '$': 41, '$$$': 3, '$$$$': 3}, 'Fullerton,CA': {'$$': 59, '$': 33, '$$$': 3, '$$$$': 1}, 'Costa Mesa,CA': {'$$': 70, '$': 23, '$$$': 5, '$$$$': 2}, 'Mission Viejo,CA': {'$': 37, '$$': 58, '$$$': 2}, 'Westminster,CA': {'$$': 46, '$': 51, '$$$$': 2}}

In [5]:

DF=pd.DataFrame.from_dict(price_locations).T #.T means transpose, switch columns and rows
DF = DF.reset_index()
# df.rename(columns = {'index':'City','$':'Cheap'}, inplace = True)
df = DF.rename(columns={"$":"Cheap","$$":"Affordable","$$$":"Expensive","$$$$":"Luxury","index":"City"})
# DF.to_csv("output.csv")

df = df.fillna(0)
df

                  City  Cheap  Affordable  Expensive  Luxury
0           Anaheim,CA   31.0        58.0        8.0     3.0
1        Costa Mesa,CA   23.0        70.0        5.0     2.0
2         Fullerton,CA   33.0        59.0        3.0     1.0
3      Garden Grove,CA   51.0        45.0        1.0     2.0
4  Huntington Beach,CA   25.0        69.0        4.0     0.0
5            Irvine,CA   22.0        70.0        7.0     0.0
6     Mission Viejo,CA   37.0        58.0        2.0     0.0
7            Orange,CA   41.0        52.0        3.0     3.0
8         Santa Ana,CA   43.0        53.0        1.0     1.0
9       Westminster,CA   51.0        46.0        0.0     2.0